"""Add upload_type column and make drive_url nullable

Revision ID: 27ba93894213
Revises: a1b2c3d4e5f6
Create Date: 2026-02-08 19:59:48.466437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27ba93894213'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_type', sa.String(length=20), nullable=True, server_default='drive'))
        batch_op.alter_column('drive_url',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.alter_column('drive_url',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
        batch_op.drop_column('upload_type')

    # ### end Alembic commands ###
